import { EXERCISE_FORCE_TYPE, EXERCISE_TYPE } from '#/api/type';

export const EXERCISE_TYPE_OPTION = [
  { value: EXERCISE_TYPE.WEIGHT, name: EXERCISE_TYPE.WEIGHT },
  { value: EXERCISE_TYPE.CARDIO, name: EXERCISE_TYPE.CARDIO },
];

export const EXERCISE_FORCE_OPTION = [
  { value: EXERCISE_FORCE_TYPE.EASY, name: EXERCISE_FORCE_TYPE.EASY },
  {
    value: EXERCISE_FORCE_TYPE.MEDIUM,
    name: EXERCISE_FORCE_TYPE.MEDIUM,
  },
  { value: EXERCISE_FORCE_TYPE.HARD, name: EXERCISE_FORCE_TYPE.HARD },
];

export const LANGUAGE = ['en', 'ko'];
